---
- name: Initialise channels name to id mapping
  set_fact:
    channel_mapping: {}

- name: Create channels
  include: create_channels.yml
  with_items: "{{ slack_channels }}"
  loop_control:
    loop_var: channel

- name: Invite users
  include: invite_users.yml
  with_items: "{{ slack_users }}"
  loop_control:
    loop_var: user
